# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/cobr3x/C++/Monopoly Test"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/cobr3x/C++/Monopoly Test"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/cobr3x/C++/Monopoly Test/CMakeFiles" "/home/cobr3x/C++/Monopoly Test//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/cobr3x/C++/Monopoly Test/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named monopoly

# Build rule for target.
monopoly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monopoly
.PHONY : monopoly

# fast build rule for target.
monopoly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/build
.PHONY : monopoly/fast

src/AngularBox.o: src/AngularBox.cpp.o
.PHONY : src/AngularBox.o

# target to build an object file
src/AngularBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/AngularBox.cpp.o
.PHONY : src/AngularBox.cpp.o

src/AngularBox.i: src/AngularBox.cpp.i
.PHONY : src/AngularBox.i

# target to preprocess a source file
src/AngularBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/AngularBox.cpp.i
.PHONY : src/AngularBox.cpp.i

src/AngularBox.s: src/AngularBox.cpp.s
.PHONY : src/AngularBox.s

# target to generate assembly for a file
src/AngularBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/AngularBox.cpp.s
.PHONY : src/AngularBox.cpp.s

src/GameBoard.o: src/GameBoard.cpp.o
.PHONY : src/GameBoard.o

# target to build an object file
src/GameBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/GameBoard.cpp.o
.PHONY : src/GameBoard.cpp.o

src/GameBoard.i: src/GameBoard.cpp.i
.PHONY : src/GameBoard.i

# target to preprocess a source file
src/GameBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/GameBoard.cpp.i
.PHONY : src/GameBoard.cpp.i

src/GameBoard.s: src/GameBoard.cpp.s
.PHONY : src/GameBoard.s

# target to generate assembly for a file
src/GameBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/GameBoard.cpp.s
.PHONY : src/GameBoard.cpp.s

src/LateralBox.o: src/LateralBox.cpp.o
.PHONY : src/LateralBox.o

# target to build an object file
src/LateralBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/LateralBox.cpp.o
.PHONY : src/LateralBox.cpp.o

src/LateralBox.i: src/LateralBox.cpp.i
.PHONY : src/LateralBox.i

# target to preprocess a source file
src/LateralBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/LateralBox.cpp.i
.PHONY : src/LateralBox.cpp.i

src/LateralBox.s: src/LateralBox.cpp.s
.PHONY : src/LateralBox.s

# target to generate assembly for a file
src/LateralBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/LateralBox.cpp.s
.PHONY : src/LateralBox.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monopoly.dir/build.make CMakeFiles/monopoly.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... monopoly"
	@echo "... src/AngularBox.o"
	@echo "... src/AngularBox.i"
	@echo "... src/AngularBox.s"
	@echo "... src/GameBoard.o"
	@echo "... src/GameBoard.i"
	@echo "... src/GameBoard.s"
	@echo "... src/LateralBox.o"
	@echo "... src/LateralBox.i"
	@echo "... src/LateralBox.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

